prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  nodeExporter:
    enabled: false


grafana:
  server:
    root_url:https://www.karkaushal.in/monitor/grafana
  ingress:
    enabled: true